//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CielBijou.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentaire
    {
        public int id { get; set; }
        public int un_produit_id { get; set; }
        public int un_client_id { get; set; }
        public System.DateTime date_commentaire { get; set; }
        public Nullable<bool> status_commentaire { get; set; }
        public string contenu_commentaire { get; set; }
        public Nullable<int> note_commentaire { get; set; }
    
        public virtual client client { get; set; }
        public virtual produit produit { get; set; }
    }
}
