//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CielBijou.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int id { get; set; }
        public int une_categorie_id { get; set; }
        public System.DateTime date_debut_promo { get; set; }
        public System.DateTime date_fin_promo { get; set; }
        public decimal remise_promo { get; set; }
    
        public virtual categorie categorie { get; set; }
    }
}
